### ISSUE TITLE
直接从旧版Python升级到nodejs会出现Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by Oyami-Srk** [LoliLin/CloudMan#3]
```
(.venv) MusicDB/CloudMan >  npm start                                                 node * 23:54:15 [0]

> cloudman@0.6.2 start /Volumes/MusicDB/CloudMan
> node app.js

[2020-07-15T15:58:15.606Z] [INFO] Getting downloaded tracks...
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '/Volumes/MusicDB/MUSIC/CloudMan/MUSIC/1049192.flac'
    at Object.readdirSync (fs.js:974:3)
    at Object.<anonymous> (/Volumes/MusicDB/CloudMan/app.js:40:25)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/Volumes/MusicDB/MUSIC/CloudMan/MUSIC/1049192.flac'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloudman@0.6.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloudman@0.6.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shiroko/.npm/_logs/2020-07-15T15_58_15_621Z-debug.log
(.venv) MusicDB/CloudMan >                                          
```

**Comment by LynMoe** [comment]
新版的程序在存音乐的时候是用了 `/MUSIC/{hash 前两位}/{网易云 id}.flac` 来存的，主要是为了防止一个目录下文件太多对文件系统不好，建议全部删掉再试一遍
